# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  before_all do
    setup_circle_ci
  end

  # desc "Increment version code"
  # lane :increment_vc do
  #   increment_version_code(
  #     gradle_file_path: "./app/build.gradle",
  #   )
  # end

  desc "Build release apk"
  lane :build_apk do
    gradle(task: "clean assembleRelease")
  end

  desc "Build release app bundle"
  lane :build_bundle do
    gradle(task: "clean bundleRelease")
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to AppCenter"
  lane :beta do
    build_apk
    # appcenter_upload(
    #   api_token: "<appcenter token>",
    #   owner_name: "<appcenter account name of the owner of the app (username or organization URL name)>",
    #   owner_type: "user", # Default is user - set to organization for appcenter organizations
    #   app_name: "<appcenter app name (as seen in app URL)>",
    #   file: "<path to android build binary>",
    #   notify_testers: false # Set to false if you don't want to notify testers of your new release (default: `false`)
    # )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # The lane you created previously to increment your app’s `version code`.
    # increment_vc
    # The build release app bundle lane you created previously.
    build_bundle
    # Uploads Android App Bundle to Play Console.
    upload_to_play_store(release_status:"draft", track: "internal")
  end
end
